### ISSUE TITLE
Methods mixed with operator fail in the typechecker

### ISSUE THREAD

**Issue by flofriday** [flofriday/Moose#27]
## Example
![image](https://user-images.githubusercontent.com/21206831/188895530-6440210a-64b1-491c-875f-13cd126ddea4.png)

## Note
You have to ignore the three lines before the error, its just some debug output.

Also the error highlighting is kinda messed up which shouldn't happen.

**Comment by Jozott00** [comment]
The problem lies at the parser... it parses `2.(toString() +  " two")` instead of `(2.toString()) + " two"`

**Comment by Jozott00** [comment]
Ok I solved the problem. The current precendence was determined at the wrong place, so it wasn't right. Fix was a oneliner.

Now we get the following typechecker error:
```

  1| print(2.toString() + " two")
           ^^^^^^^^^^

Function calls are only valid for identifiers, not for `2.toString`
```

**Comment by flofriday** [comment]
True, yes disable that. A couple of weeks I moved that check from the parser to the typechecket (and made it more lax) but I don't think it should be there at all.

**Comment by Jozott00** [comment]
Actually this constraint is true, in the above example, the parsing predendence was still wrong, since it parsed the dereference before the call. The constraint just says that is only possible to call a function by a name. This wouldn't be the case if we would have higher order function, but right now this holds true.
